config/routes.rb
Rails.application.routes.draw do
  #API
  namespace :api, defaults: { format: :json } do
    get '/paolofox' => 'gifts#new'
  end

  #WebApp
  get 'users/index'
  get 'users/show'
  devise_for :users

  root 'home#main'

  resources :users, only: [ :index ]
  resources :gifts, except: [ :edit, :update ]

  resources :whies, except: [ :show ]
  resources :whats, except: [ :show ]
  resources :whos, except: [ :show ]
end

app/models/gift.rb
class Gift < ApplicationRecord
  belongs_to :who
  belongs_to :what
  belongs_to :why
  belongs_to :user

  def self.generate
    who = Who.random_instance
    what = What.random_instance
    why = Why.random_instance
    return self.new(who: who, what: what, why: why)
  end
end

app/controllers/api/gifts_controller.rb
class Api::GiftsController < Api::ApiController
	def new
		gift = Gift.generate
		render json: { content: "#{gift.who.content} #{gift.what.content}, #{gift.why.content}" }
	end
end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
  before_action :set_gift, only: %i[ destroy ]
  load_and_authorize_resource

  # GET /gifts or /gifts.json
  def index

    @user = ( params[:user_id] ? User.find(params[:user_id]) : current_user )

    @gifts = Gift.where(user_id: @user&.id)
  end

  # GET /gifts/new
  def new
    @gift = Gift.generate
  end

  # POST /gifts or /gifts.json
  def create
    @gift = Gift.new(gift_params)

    respond_to do |format|
      if @gift.save
        format.html { redirect_to root_path, notice: "Gift was successfully created." }
        format.json { render :index, status: :created, location: @gift }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @gift.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gifts/1 or /gifts/1.json
  def destroy
    @gift.destroy
    respond_to do |format|
      format.html { redirect_to gifts_url, notice: "Gift was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gift
      @gift = Gift.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def gift_params
      params.require(:gift).permit(:who_id, :what_id, :why_id, :user_id)
    end
end

app/helpers/gifts_helper.rb
module GiftsHelper
end

app/views/gifts/_form.html.erb
<%= form_with(model: gift) do |form| %>
  <% if gift.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gift.errors.count, "error") %> prohibited this gift from being saved:</h2>

      <ul>
        <% gift.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.hidden_field :who_id %>

    <%= form.hidden_field :what_id %>

    <%= form.hidden_field :why_id %>
  </div>
  <div class="actions">
    <%= link_to "<i class='fas fa-level-down-alt rotate90'></i>".html_safe, root_path, class:"btn btn-run back" %>
    <td><%= link_to '', root_path, class:" icon" %></td>
    <%if user_signed_in? %>
      <%= form.hidden_field :user_id, value: current_user.id %>

      <%= form.submit "Save Gift", class:"btn btn-fight"%>
    <% end %>
  </div>
<% end %>

app/views/gifts/edit.html.erb
<h1>Editing Gift</h1>

<%= render 'form', gift: @gift %>

<%= link_to 'Show', @gift %> |
<%= link_to 'Back', gifts_path %>

app/views/gifts/index.html.erb
<p id="notice"><%= notice %></p>

<% if !user_signed_in? %>
  <h4>In order to view saved gifts, first <%=link_to "Sign in", new_user_session_path %></h4>
<% else %>
  <h2><%=@user.username %>'s gifts</h2>

  <table class="table table-dark">

    <% if current_user.admin? %>
      <thead>
        <tr>
          <td><%= link_to 'list of Whos', whos_path, class:'btn btn-sm btn-pieces' %></td>
          <td><%= link_to 'list of Whats', whats_path, class:'btn btn-sm btn-pieces' %></td>
          <td><%= link_to 'list of Whies', whies_path, class:'btn btn-sm btn-pieces' %></td>
          <td></td>
        </tr>
      </thead>
    <% end %>
    <tbody>
      <% if @gifts.empty? %>
        <tr><td colspan="4">No saved gifts for this user</td></tr>
      <% else %>
        <% @gifts.each do |gift| %>
          <tr>
            <td><%= gift.who.content %></td>
            <td><%= gift.what.content %></td>
            <td><%= gift.why.content %></td>
            <% if current_user.id == @user.id || current_user.admin?%>
              <td><%= link_to '', gift, method: :delete, data: { confirm: 'Are you sure?' }, class:"fa fa-trash icon" %></td>
            <% end %>
          </tr>
        <% end %>
      <% end %>

    </tbody>
  </table>
<% end %>
<%= link_to "<i class='fas fa-level-down-alt rotate90'></i>".html_safe, root_path, class:"btn btn-run back" %>

app/views/gifts/new.html.erb
<div class="gift">
  <div class="messages">
    <div></div>
    <%= text_field :post, :who_content, value: @gift.who.content, readonly: true, class:"form-control form-control-sm message"%>
    <%= text_field :post, :what_content, value: @gift.what.content, readonly: true, class:"form-control form-control-sm message"%>
    <%= text_field :post, :why_content, value: @gift.why.content, readonly: true, class:"form-control form-control-sm message"%>
  </div>
</div>

<%= render 'form', gift: @gift %>